### PR TITLE
Add options to modify the name of the unreved/reved files before using them

### PR DESCRIPTION
**Pull request by mrkipling**
This PR adds two new options: `modifyReved` and `modifyUnreved`.

I have updated the README to explain in more detail what is happening here. There are only a few new lines of code so hopefully they should be fairly self-explanatory.

### CODE REVIEW

**Comment by mrkipling** [comment]
Hi - any word on this?

I needed to add this feature in order to get sourcemaps working for our build. Am currently using our fork but it would obviously be good if it were merged.

**Comment by jamesknelson-misoca** [comment]
Wouldn't hurt if it had tests.

**Comment by jamesknelson** [comment]
I like this implementation, it seems flexible and is pretty easy to understand. If you can add tests, I'd be happy to merge it.

**Comment by mrkipling** [comment]
Sorry for the delay - have just pushed some tests that check modifyReved and modifyUnreved work as expected.

**Comment by jamesknelson** [comment]
Thanks, merged!

**Comment by mrkipling** [comment]
Thanks!

**Comment by mrkipling** [comment]
Would it be possible to update this on npm? Or is that an automatic process? (I don't have much experience publishing to npm myself)

**Comment by jamesknelson** [comment]
It totally slipped my mind, thanks for reminding me. I've just published 0.4.2.

**Comment by mrkipling** [comment]
Excellent, thank you.

**Pull request merged**
