### PR TITLE
Invoke JSHint suring running of tests

### PR DESCRIPTION
**Pull request by SimenB**
I was thinking of contributing, and noticed that while you have a .jshintrc, it's never used during the build.

It still doesn't cleanly exit, even though I made a couple of changes (as you can probably see from Travis), but I'm unsure if you want to fix the errors or ignore them. Instead of spending time on it, I'll just wait for your input on it before making it pass. :smile:

### CODE REVIEW

**Comment by SimenB** [comment]
@jamesknelson ping :smile:

**Comment by jamesknelson** [comment]
@SimenB, I'm not personally a huge JSHint fan - the .jshintrc crept through on a previous pull request. I'll remove it and close this.

**Comment by SimenB** [comment]
Ok, that's fine :smile: 

Curiosity: why don't you like linting?

**Comment by jamesknelson** [comment]
It isn't linting I'm against so much as the fact that I'm not a huge fan of the style which JSHint enforces, and I feel it is more work to make code confirm than it is to fix any bugs which appear. Also, for other projects, I generally use coffeescript, which I feel is a much nicer solution to the same problem.

**Pull request closed without merging**
