### PR TITLE
Added prefix support

### PR DESCRIPTION
**Pull request by aquilax**
This PR adds `prefix` option that allows the user to add custom prefix to every replaced file name e.g. CDN url.

Example usage:
```js
gulp.src('index.html')
  .pipe(revReplace({prefix: 'http://example.com'})
  .pipe(gulp.dest('build'));
```

### CODE REVIEW

**Comment by Cheguevara** [comment]
It's a very useful feature. When you will merge it?

**Comment by jamesknelson** [comment]
I don't have time to manually resolve the conflicts with the latest master myself at the moment, but if somebody can do that for me I'll merge it, as it does look like some people would find it useful.

**Comment by aquilax** [comment]
The branch was merged to the latest master and version was bumped to `0.3.3`

/ping @jamesknelson

**Comment by jamesknelson** [comment]
Thanks aquilax!

**Pull request merged**
